DROP TABLE IF EXISTS local_authorities;
DROP TABLE IF EXISTS care_provider_locations;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS postcodes;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS care_providers;
DROP TABLE IF EXISTS geo_data;


-- Start script

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE care_providers (
                                id integer GENERATED BY DEFAULT AS IDENTITY,
                                name character varying(100) NOT NULL,
                                code character varying(15) NOT NULL,
                                loaded_datetime timestamp with time zone NOT NULL,
                                CONSTRAINT "PK_care_providers" PRIMARY KEY (id)
);

CREATE TABLE geo_data (
                          id integer GENERATED BY DEFAULT AS IDENTITY,
                          coordinate geometry (point) NOT NULL,
                          bounding_polygon geometry (polygon),
                          code character varying(15) NOT NULL,
                          loaded_datetime timestamp with time zone NOT NULL,
                          CONSTRAINT "PK_geo_data" PRIMARY KEY (id)
);

CREATE TABLE metric_groups (
                               id integer GENERATED BY DEFAULT AS IDENTITY,
                               name character varying(100) NOT NULL,
                               code character varying(15) NOT NULL,
                               loaded_datetime timestamp with time zone NOT NULL,
                               CONSTRAINT "PK_metric_groups" PRIMARY KEY (id)
);

CREATE TABLE countries (
                           id integer GENERATED BY DEFAULT AS IDENTITY,
                           name character varying(60) NOT NULL,
                           geo_data_fk integer NOT NULL,
                           code character varying(15) NOT NULL,
                           loaded_datetime timestamp with time zone NOT NULL,
                           CONSTRAINT "PK_countries" PRIMARY KEY (id),
                           CONSTRAINT "FK_countries_geo_data_geo_data_fk" FOREIGN KEY (geo_data_fk) REFERENCES geo_data (id) ON DELETE CASCADE
);

CREATE TABLE metrics (
                         id integer GENERATED BY DEFAULT AS IDENTITY,
                         name character varying(100) NOT NULL,
                         metric_group_fk integer NOT NULL,
                         display_name character varying(255) NOT NULL,
                         numerator_description character varying(255) NOT NULL,
                         denominator_description character varying(255) NOT NULL,
                         data_source character varying(40) NOT NULL,
                         data_type character varying(50) NOT NULL,
                         frequency character varying(25) NOT NULL,
                         code character varying(15) NOT NULL,
                         loaded_datetime timestamp with time zone NOT NULL,
                         CONSTRAINT "PK_metrics" PRIMARY KEY (id),
                         CONSTRAINT "FK_metrics_metric_groups_metric_group_fk" FOREIGN KEY (metric_group_fk) REFERENCES metric_groups (id) ON DELETE CASCADE
);

CREATE TABLE regions (
                         id integer GENERATED BY DEFAULT AS IDENTITY,
                         name character varying(50) NOT NULL,
                         country_fk integer NOT NULL,
                         geo_data_fk integer NOT NULL,
                         code character varying(15) NOT NULL,
                         loaded_datetime timestamp with time zone NOT NULL,
                         CONSTRAINT "PK_regions" PRIMARY KEY (id),
                         CONSTRAINT "FK_regions_countries_country_fk" FOREIGN KEY (country_fk) REFERENCES countries (id) ON DELETE CASCADE,
                         CONSTRAINT "FK_regions_geo_data_geo_data_fk" FOREIGN KEY (geo_data_fk) REFERENCES geo_data (id) ON DELETE CASCADE
);

CREATE TABLE bedcount (
                          id integer GENERATED BY DEFAULT AS IDENTITY,
                          code character varying(15) NOT NULL,
                          loaded_datetime timestamp with time zone NOT NULL,
                          start_date timestamp with time zone NOT NULL,
                          end_date timestamp with time zone NOT NULL,
                          location_fk text NOT NULL,
                          location_type text NOT NULL,
                          metric_fk integer NOT NULL,
                          time_series numeric[] NOT NULL,
                          latest_value numeric NOT NULL,
                          CONSTRAINT "PK_bedcount" PRIMARY KEY (id),
                          CONSTRAINT "FK_bedcount_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE bedcount_per_hundred_thousand_adults (
                                                      id integer GENERATED BY DEFAULT AS IDENTITY,
                                                      code character varying(15) NOT NULL,
                                                      loaded_datetime timestamp with time zone NOT NULL,
                                                      start_date timestamp with time zone NOT NULL,
                                                      end_date timestamp with time zone NOT NULL,
                                                      location_fk text NOT NULL,
                                                      location_type text NOT NULL,
                                                      metric_fk integer NOT NULL,
                                                      time_series numeric[] NOT NULL,
                                                      latest_value numeric NOT NULL,
                                                      CONSTRAINT "PK_bedcount_per_hundred_thousand_adults" PRIMARY KEY (id),
                                                      CONSTRAINT "FK_bedcount_per_hundred_thousand_adults_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE dementia_estimated_diagnosis_rate_65over (
                                                          id integer GENERATED BY DEFAULT AS IDENTITY,
                                                          code character varying(15) NOT NULL,
                                                          loaded_datetime timestamp with time zone NOT NULL,
                                                          start_date timestamp with time zone NOT NULL,
                                                          end_date timestamp with time zone NOT NULL,
                                                          location_fk text NOT NULL,
                                                          location_type text NOT NULL,
                                                          metric_fk integer NOT NULL,
                                                          time_series numeric[] NOT NULL,
                                                          latest_value numeric NOT NULL,
                                                          CONSTRAINT "PK_dementia_estimated_diagnosis_rate_65over" PRIMARY KEY (id),
                                                          CONSTRAINT "FK_dementia_estimated_diagnosis_rate_65over_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE dementia_prevalence_65over (
                                            id integer GENERATED BY DEFAULT AS IDENTITY,
                                            code character varying(15) NOT NULL,
                                            loaded_datetime timestamp with time zone NOT NULL,
                                            start_date timestamp with time zone NOT NULL,
                                            end_date timestamp with time zone NOT NULL,
                                            location_fk text NOT NULL,
                                            location_type text NOT NULL,
                                            metric_fk integer NOT NULL,
                                            time_series numeric[] NOT NULL,
                                            latest_value numeric NOT NULL,
                                            CONSTRAINT "PK_dementia_prevalence_65over" PRIMARY KEY (id),
                                            CONSTRAINT "FK_dementia_prevalence_65over_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE dementia_qof_prevalence (
                                         id integer GENERATED BY DEFAULT AS IDENTITY,
                                         code character varying(15) NOT NULL,
                                         loaded_datetime timestamp with time zone NOT NULL,
                                         start_date timestamp with time zone NOT NULL,
                                         end_date timestamp with time zone NOT NULL,
                                         location_fk text NOT NULL,
                                         location_type text NOT NULL,
                                         metric_fk integer NOT NULL,
                                         time_series numeric[] NOT NULL,
                                         latest_value numeric NOT NULL,
                                         CONSTRAINT "PK_dementia_qof_prevalence" PRIMARY KEY (id),
                                         CONSTRAINT "FK_dementia_qof_prevalence_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE dementia_register_65over_per100k (
                                                  id integer GENERATED BY DEFAULT AS IDENTITY,
                                                  code character varying(15) NOT NULL,
                                                  loaded_datetime timestamp with time zone NOT NULL,
                                                  start_date timestamp with time zone NOT NULL,
                                                  end_date timestamp with time zone NOT NULL,
                                                  location_fk text NOT NULL,
                                                  location_type text NOT NULL,
                                                  metric_fk integer NOT NULL,
                                                  time_series numeric[] NOT NULL,
                                                  latest_value numeric NOT NULL,
                                                  CONSTRAINT "PK_dementia_register_65over_per100k" PRIMARY KEY (id),
                                                  CONSTRAINT "FK_dementia_register_65over_per100k_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE learning_disability_prevalence (
                                                id integer GENERATED BY DEFAULT AS IDENTITY,
                                                code character varying(15) NOT NULL,
                                                loaded_datetime timestamp with time zone NOT NULL,
                                                start_date timestamp with time zone NOT NULL,
                                                end_date timestamp with time zone NOT NULL,
                                                location_fk text NOT NULL,
                                                location_type text NOT NULL,
                                                metric_fk integer NOT NULL,
                                                time_series numeric[] NOT NULL,
                                                latest_value numeric NOT NULL,
                                                CONSTRAINT "PK_learning_disability_prevalence" PRIMARY KEY (id),
                                                CONSTRAINT "FK_learning_disability_prevalence_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE median_bed_count (
                                  id integer GENERATED BY DEFAULT AS IDENTITY,
                                  code character varying(15) NOT NULL,
                                  loaded_datetime timestamp with time zone NOT NULL,
                                  start_date timestamp with time zone NOT NULL,
                                  end_date timestamp with time zone NOT NULL,
                                  location_fk text NOT NULL,
                                  location_type text NOT NULL,
                                  metric_fk integer NOT NULL,
                                  time_series numeric[] NOT NULL,
                                  latest_value numeric NOT NULL,
                                  CONSTRAINT "PK_median_bed_count" PRIMARY KEY (id),
                                  CONSTRAINT "FK_median_bed_count_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE median_occupancy (
                                  id integer GENERATED BY DEFAULT AS IDENTITY,
                                  code character varying(15) NOT NULL,
                                  loaded_datetime timestamp with time zone NOT NULL,
                                  start_date timestamp with time zone NOT NULL,
                                  end_date timestamp with time zone NOT NULL,
                                  location_fk text NOT NULL,
                                  location_type text NOT NULL,
                                  metric_fk integer NOT NULL,
                                  time_series numeric[] NOT NULL,
                                  latest_value numeric NOT NULL,
                                  CONSTRAINT "PK_median_occupancy" PRIMARY KEY (id),
                                  CONSTRAINT "FK_median_occupancy_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE occupancy_rates (
                                 id integer GENERATED BY DEFAULT AS IDENTITY,
                                 code character varying(15) NOT NULL,
                                 loaded_datetime timestamp with time zone NOT NULL,
                                 start_date timestamp with time zone NOT NULL,
                                 end_date timestamp with time zone NOT NULL,
                                 location_fk text NOT NULL,
                                 location_type text NOT NULL,
                                 metric_fk integer NOT NULL,
                                 time_series numeric[] NOT NULL,
                                 latest_value numeric NOT NULL,
                                 CONSTRAINT "PK_occupancy_rates" PRIMARY KEY (id),
                                 CONSTRAINT "FK_occupancy_rates_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_18_64 (
                            id integer GENERATED BY DEFAULT AS IDENTITY,
                            code character varying(15) NOT NULL,
                            loaded_datetime timestamp with time zone NOT NULL,
                            start_date timestamp with time zone NOT NULL,
                            end_date timestamp with time zone NOT NULL,
                            location_fk text NOT NULL,
                            location_type text NOT NULL,
                            metric_fk integer NOT NULL,
                            time_series numeric[] NOT NULL,
                            latest_value numeric NOT NULL,
                            CONSTRAINT "PK_perc_18_64" PRIMARY KEY (id),
                            CONSTRAINT "FK_perc_18_64_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_65over (
                             id integer GENERATED BY DEFAULT AS IDENTITY,
                             code character varying(15) NOT NULL,
                             loaded_datetime timestamp with time zone NOT NULL,
                             start_date timestamp with time zone NOT NULL,
                             end_date timestamp with time zone NOT NULL,
                             location_fk text NOT NULL,
                             location_type text NOT NULL,
                             metric_fk integer NOT NULL,
                             time_series numeric[] NOT NULL,
                             latest_value numeric NOT NULL,
                             CONSTRAINT "PK_perc_65over" PRIMARY KEY (id),
                             CONSTRAINT "FK_perc_65over_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_75over (
                             id integer GENERATED BY DEFAULT AS IDENTITY,
                             code character varying(15) NOT NULL,
                             loaded_datetime timestamp with time zone NOT NULL,
                             start_date timestamp with time zone NOT NULL,
                             end_date timestamp with time zone NOT NULL,
                             location_fk text NOT NULL,
                             location_type text NOT NULL,
                             metric_fk integer NOT NULL,
                             time_series numeric[] NOT NULL,
                             latest_value numeric NOT NULL,
                             CONSTRAINT "PK_perc_75over" PRIMARY KEY (id),
                             CONSTRAINT "FK_perc_75over_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_85over (
                             id integer GENERATED BY DEFAULT AS IDENTITY,
                             code character varying(15) NOT NULL,
                             loaded_datetime timestamp with time zone NOT NULL,
                             start_date timestamp with time zone NOT NULL,
                             end_date timestamp with time zone NOT NULL,
                             location_fk text NOT NULL,
                             location_type text NOT NULL,
                             metric_fk integer NOT NULL,
                             time_series numeric[] NOT NULL,
                             latest_value numeric NOT NULL,
                             CONSTRAINT "PK_perc_85over" PRIMARY KEY (id),
                             CONSTRAINT "FK_perc_85over_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_general_health (
                                     id integer GENERATED BY DEFAULT AS IDENTITY,
                                     code character varying(15) NOT NULL,
                                     loaded_datetime timestamp with time zone NOT NULL,
                                     start_date timestamp with time zone NOT NULL,
                                     end_date timestamp with time zone NOT NULL,
                                     location_fk text NOT NULL,
                                     location_type text NOT NULL,
                                     metric_fk integer NOT NULL,
                                     time_series numeric[] NOT NULL,
                                     latest_value numeric NOT NULL,
                                     CONSTRAINT "PK_perc_general_health" PRIMARY KEY (id),
                                     CONSTRAINT "FK_perc_general_health_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_household_ownership (
                                          id integer GENERATED BY DEFAULT AS IDENTITY,
                                          code character varying(15) NOT NULL,
                                          loaded_datetime timestamp with time zone NOT NULL,
                                          start_date timestamp with time zone NOT NULL,
                                          end_date timestamp with time zone NOT NULL,
                                          location_fk text NOT NULL,
                                          location_type text NOT NULL,
                                          metric_fk integer NOT NULL,
                                          time_series numeric[] NOT NULL,
                                          latest_value numeric NOT NULL,
                                          CONSTRAINT "PK_perc_household_ownership" PRIMARY KEY (id),
                                          CONSTRAINT "FK_perc_household_ownership_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_households_deprivation_deprived (
                                                      id integer GENERATED BY DEFAULT AS IDENTITY,
                                                      code character varying(15) NOT NULL,
                                                      loaded_datetime timestamp with time zone NOT NULL,
                                                      start_date timestamp with time zone NOT NULL,
                                                      end_date timestamp with time zone NOT NULL,
                                                      location_fk text NOT NULL,
                                                      location_type text NOT NULL,
                                                      metric_fk integer NOT NULL,
                                                      time_series numeric[] NOT NULL,
                                                      latest_value numeric NOT NULL,
                                                      CONSTRAINT "PK_perc_households_deprivation_deprived" PRIMARY KEY (id),
                                                      CONSTRAINT "FK_perc_households_deprivation_deprived_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_households_one_person (
                                            id integer GENERATED BY DEFAULT AS IDENTITY,
                                            code character varying(15) NOT NULL,
                                            loaded_datetime timestamp with time zone NOT NULL,
                                            start_date timestamp with time zone NOT NULL,
                                            end_date timestamp with time zone NOT NULL,
                                            location_fk text NOT NULL,
                                            location_type text NOT NULL,
                                            metric_fk integer NOT NULL,
                                            time_series numeric[] NOT NULL,
                                            latest_value numeric NOT NULL,
                                            CONSTRAINT "PK_perc_households_one_person" PRIMARY KEY (id),
                                            CONSTRAINT "FK_perc_households_one_person_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_population_disability (
                                            id integer GENERATED BY DEFAULT AS IDENTITY,
                                            code character varying(15) NOT NULL,
                                            loaded_datetime timestamp with time zone NOT NULL,
                                            start_date timestamp with time zone NOT NULL,
                                            end_date timestamp with time zone NOT NULL,
                                            location_fk text NOT NULL,
                                            location_type text NOT NULL,
                                            metric_fk integer NOT NULL,
                                            time_series numeric[] NOT NULL,
                                            latest_value numeric NOT NULL,
                                            CONSTRAINT "PK_perc_population_disability" PRIMARY KEY (id),
                                            CONSTRAINT "FK_perc_population_disability_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE perc_unpaid_care_provider (
                                           id integer GENERATED BY DEFAULT AS IDENTITY,
                                           code character varying(15) NOT NULL,
                                           loaded_datetime timestamp with time zone NOT NULL,
                                           start_date timestamp with time zone NOT NULL,
                                           end_date timestamp with time zone NOT NULL,
                                           location_fk text NOT NULL,
                                           location_type text NOT NULL,
                                           metric_fk integer NOT NULL,
                                           time_series numeric[] NOT NULL,
                                           latest_value numeric NOT NULL,
                                           CONSTRAINT "PK_perc_unpaid_care_provider" PRIMARY KEY (id),
                                           CONSTRAINT "FK_perc_unpaid_care_provider_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE total_population (
                                  id integer GENERATED BY DEFAULT AS IDENTITY,
                                  code character varying(15) NOT NULL,
                                  loaded_datetime timestamp with time zone NOT NULL,
                                  start_date timestamp with time zone NOT NULL,
                                  end_date timestamp with time zone NOT NULL,
                                  location_fk text NOT NULL,
                                  location_type text NOT NULL,
                                  metric_fk integer NOT NULL,
                                  time_series numeric[] NOT NULL,
                                  latest_value numeric NOT NULL,
                                  CONSTRAINT "PK_total_population" PRIMARY KEY (id),
                                  CONSTRAINT "FK_total_population_metrics_metric_fk" FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE
);

CREATE TABLE local_authorities (
                                   id integer GENERATED BY DEFAULT AS IDENTITY,
                                   name character varying(50) NOT NULL,
                                   region_fk integer NOT NULL,
                                   geo_data_fk integer NOT NULL,
                                   code character varying(15) NOT NULL,
                                   loaded_datetime timestamp with time zone NOT NULL,
                                   CONSTRAINT "PK_local_authorities" PRIMARY KEY (id),
                                   CONSTRAINT "FK_local_authorities_geo_data_geo_data_fk" FOREIGN KEY (geo_data_fk) REFERENCES geo_data (id) ON DELETE CASCADE,
                                   CONSTRAINT "FK_local_authorities_regions_region_fk" FOREIGN KEY (region_fk) REFERENCES regions (id) ON DELETE CASCADE
);

CREATE TABLE care_provider_locations (
                                         id integer GENERATED BY DEFAULT AS IDENTITY,
                                         name character varying(100) NOT NULL,
                                         care_provider_fk integer NOT NULL,
                                         address character varying(255) NOT NULL,
                                         nominated_individual character varying(255) NOT NULL,
                                         local_authority_fk integer NOT NULL,
                                         geo_data_fk integer NOT NULL,
                                         code character varying(15) NOT NULL,
                                         loaded_datetime timestamp with time zone NOT NULL,
                                         CONSTRAINT "PK_care_provider_locations" PRIMARY KEY (id),
                                         CONSTRAINT "FK_care_provider_locations_care_providers_care_provider_fk" FOREIGN KEY (care_provider_fk) REFERENCES care_providers (id) ON DELETE CASCADE,
                                         CONSTRAINT "FK_care_provider_locations_geo_data_geo_data_fk" FOREIGN KEY (geo_data_fk) REFERENCES geo_data (id) ON DELETE CASCADE,
                                         CONSTRAINT "FK_care_provider_locations_local_authorities_local_authority_fk" FOREIGN KEY (local_authority_fk) REFERENCES local_authorities (id) ON DELETE CASCADE
);

CREATE TABLE postcodes (
                           id integer GENERATED BY DEFAULT AS IDENTITY,
                           display_postcode character varying(8) NOT NULL,
                           local_authority_fk integer NOT NULL,
                           geo_data_fk integer NOT NULL,
                           code character varying(15) NOT NULL,
                           loaded_datetime timestamp with time zone NOT NULL,
                           CONSTRAINT "PK_postcodes" PRIMARY KEY (id),
                           CONSTRAINT "FK_postcodes_geo_data_geo_data_fk" FOREIGN KEY (geo_data_fk) REFERENCES geo_data (id) ON DELETE CASCADE,
                           CONSTRAINT "FK_postcodes_local_authorities_local_authority_fk" FOREIGN KEY (local_authority_fk) REFERENCES local_authorities (id) ON DELETE CASCADE
);

CREATE INDEX "IX_bedcount_metric_fk" ON bedcount (metric_fk);

CREATE INDEX "IX_bedcount_per_hundred_thousand_adults_metric_fk" ON bedcount_per_hundred_thousand_adults (metric_fk);

CREATE INDEX "IX_care_provider_locations_care_provider_fk" ON care_provider_locations (care_provider_fk);

CREATE INDEX "IX_care_provider_locations_geo_data_fk" ON care_provider_locations (geo_data_fk);

CREATE INDEX "IX_care_provider_locations_local_authority_fk" ON care_provider_locations (local_authority_fk);

CREATE INDEX "IX_countries_geo_data_fk" ON countries (geo_data_fk);

CREATE INDEX "IX_dementia_estimated_diagnosis_rate_65over_metric_fk" ON dementia_estimated_diagnosis_rate_65over (metric_fk);

CREATE INDEX "IX_dementia_prevalence_65over_metric_fk" ON dementia_prevalence_65over (metric_fk);

CREATE INDEX "IX_dementia_qof_prevalence_metric_fk" ON dementia_qof_prevalence (metric_fk);

CREATE INDEX "IX_dementia_register_65over_per100k_metric_fk" ON dementia_register_65over_per100k (metric_fk);

CREATE INDEX "IX_learning_disability_prevalence_metric_fk" ON learning_disability_prevalence (metric_fk);

CREATE INDEX "IX_local_authorities_geo_data_fk" ON local_authorities (geo_data_fk);

CREATE INDEX "IX_local_authorities_region_fk" ON local_authorities (region_fk);

CREATE INDEX "IX_median_bed_count_metric_fk" ON median_bed_count (metric_fk);

CREATE INDEX "IX_median_occupancy_metric_fk" ON median_occupancy (metric_fk);

CREATE INDEX "IX_metrics_metric_group_fk" ON metrics (metric_group_fk);

CREATE INDEX "IX_occupancy_rates_metric_fk" ON occupancy_rates (metric_fk);

CREATE INDEX "IX_perc_18_64_metric_fk" ON perc_18_64 (metric_fk);

CREATE INDEX "IX_perc_65over_metric_fk" ON perc_65over (metric_fk);

CREATE INDEX "IX_perc_75over_metric_fk" ON perc_75over (metric_fk);

CREATE INDEX "IX_perc_85over_metric_fk" ON perc_85over (metric_fk);

CREATE INDEX "IX_perc_general_health_metric_fk" ON perc_general_health (metric_fk);

CREATE INDEX "IX_perc_household_ownership_metric_fk" ON perc_household_ownership (metric_fk);

CREATE INDEX "IX_perc_households_deprivation_deprived_metric_fk" ON perc_households_deprivation_deprived (metric_fk);

CREATE INDEX "IX_perc_households_one_person_metric_fk" ON perc_households_one_person (metric_fk);

CREATE INDEX "IX_perc_population_disability_metric_fk" ON perc_population_disability (metric_fk);

CREATE INDEX "IX_perc_unpaid_care_provider_metric_fk" ON perc_unpaid_care_provider (metric_fk);

CREATE INDEX "IX_postcodes_geo_data_fk" ON postcodes (geo_data_fk);

CREATE INDEX "IX_postcodes_local_authority_fk" ON postcodes (local_authority_fk);

CREATE INDEX "IX_regions_country_fk" ON regions (country_fk);

CREATE INDEX "IX_regions_geo_data_fk" ON regions (geo_data_fk);

CREATE INDEX "IX_total_population_metric_fk" ON total_population (metric_fk);


-- insert test data

DO $$
DECLARE
    country_id integer = 1;
    region_id integer = 1;
    la_id integer = 1;
    care_provider_id integer = 1;
    care_provider_id_2 integer = 2;
    care_provider_id_3 integer = 3;              
    care_provider_location_id integer = 1;
    care_provider_location_id_2 integer = 2;
    care_provider_location_id_3 integer = 3;
    gd_country integer = 1;
    gd_region integer = 2;
    gd_la integer = 3;
    gd_cpl integer = 4;
    gd_cpl_2 integer = 5;
    gd_cpl_3 integer = 6;
    gd_postcode integer = 7;
    gd_postcode_2 integer = 8;
    gd_postcode_3 integer = 9;    
    gd_postcode_4 integer = 10;

BEGIN
    INSERT INTO geo_data(id, code, coordinate, bounding_polygon, loaded_datetime)
    VALUES (gd_country, 'code', ST_Point(-1.464854, 52.561928), null, CURRENT_TIMESTAMP),
           (gd_region, 'code', ST_Point(-2.75, 54.075),ST_Polygon('LINESTRING(52.9 -3.8, 52.9 -1.8, 55.25 -1.8, 55.25 -3.8, 52.9 -3.8)'::geometry, 4326), CURRENT_TIMESTAMP),
           (gd_la, 'code', ST_Point(-2.98, 53.405),ST_Polygon('LINESTRING(53.26 -3.3, 53.26 -2.55, 53.73 -2.55, 53.73 -3.3, 53.26 -3.3)'::geometry, 4326), CURRENT_TIMESTAMP),
           (gd_cpl, 'code', ST_Point(-2.88, 53.425), ST_Polygon('LINESTRING(55.26 -3.3, 52.26 -2.55, 53.73 -2.65, 54.73 -3.3, 55.26 -3.3)'::geometry, 4326), CURRENT_TIMESTAMP),
           (gd_cpl_2, 'code', ST_Point(-2.38, 52.425), null, CURRENT_TIMESTAMP),
           (gd_cpl_3, 'code', ST_Point(-2.83, 53.425), null, CURRENT_TIMESTAMP),
           (gd_postcode, 'code', ST_Point(51.33954856349381, -0.349629386), null, CURRENT_TIMESTAMP),
           (gd_postcode_2, 'code', ST_Point( 51.32988801568501, 0.7260691453143282), null, CURRENT_TIMESTAMP),
           (gd_postcode_3, 'code', ST_Point( 51.32954649874547, 0.7283745919593453), null, CURRENT_TIMESTAMP),
           (gd_postcode_4, 'code', ST_Point(52.43602168912626, -1.445481473), null, CURRENT_TIMESTAMP);


INSERT INTO countries (id, code, name, geo_data_fk, loaded_datetime)
    VALUES (country_id, 'E92000001','England', gd_country, CURRENT_TIMESTAMP);

    INSERT INTO regions (id, code, name, country_fk, geo_data_fk, loaded_datetime)
    VALUES (region_id, 'E12000002', 'North West', country_id, gd_region,CURRENT_TIMESTAMP);

    INSERT INTO local_authorities (id, code, name, region_fk, geo_data_fk, loaded_datetime)
    VALUES (la_id, 'E08000014', 'Liverpool', region_id, gd_la, CURRENT_TIMESTAMP);

    INSERT INTO postcodes (id, code, display_postcode, local_authority_fk, geo_data_fk, loaded_datetime)
    VALUES (1, 'KT220UF', 'KT22 0UF', la_id, gd_postcode, CURRENT_TIMESTAMP),
           (2, 'ME101QX', 'ME10 1QX', la_id, gd_postcode_2,CURRENT_TIMESTAMP),
           (3, 'ME101QY', 'ME10 1QY', la_id, gd_postcode_3, CURRENT_TIMESTAMP),
           (4, 'CV22TN', 'CV2 2TN', la_id,gd_postcode_4, CURRENT_TIMESTAMP);

    INSERT INTO care_providers (id, name, code, loaded_datetime)
    VALUES (care_provider_id, 'Bupa', '1-123456789', CURRENT_TIMESTAMP),
           (care_provider_id_2, 'Katherine', '1-123456777', CURRENT_TIMESTAMP),
           (care_provider_id_3, 'Rob', '1-123456712', CURRENT_TIMESTAMP);
    INSERT INTO care_provider_locations (id, name, care_provider_fk, geo_data_fk, address, nominated_individual, local_authority_fk, code, loaded_datetime)
    VALUES (care_provider_location_id, 'Bupa Liverpool', care_provider_id, gd_cpl, 'Bupa Liverpool, CV2 2TN', 'Mr. Ice Cool', la_id, '1-222222222', CURRENT_TIMESTAMP),
           (care_provider_location_id_2, 'Katherines Teeth', care_provider_id_2, gd_cpl_2, 'Katherines Teeth, Liverpool, ME10 1QX', 'Katherine', la_id, '1-222222223', CURRENT_TIMESTAMP),
           (care_provider_location_id_3, 'Katherines Eyes', care_provider_id_2, gd_cpl_3, 'Katherines Eyes, Liverpool, ME10 1QY', 'Katherine', la_id, '1-222222224', CURRENT_TIMESTAMP);

END $$;

