services:
  api:
    image: gascd-api-image
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - LATEST_GASCD_GIT_HASH=dev-build
        - LATEST_GASCD_GIT_TAG=1.0.0
    ports:
      - "5050:5050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  
  
  generate-sql:
    build: ./DataGeneration
    container_name: generate-sql
    volumes:
      - shared-volume:/output/

  postgres:
    image: postgis/postgis:18-3.6-alpine
    platform: linux/amd64
    ports:
      - "5431:5431"
    volumes:
      - ./api.Tests/TestData/test-seed.sql:/docker-entrypoint-initdb.d/1-test-seed.sql
      - shared-volume:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=mr-ice-cool
      - POSTGRES_PASSWORD=is-rockin
      - POSTGRES_DB=gascd_data
      - PGPORT=5431
    depends_on:
      generate-sql:
        condition: service_completed_successfully
        
volumes:
  shared-volume: