services:
  api:
    image: gascd-api-image
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 5050:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  postgres:
    image: postgis/postgis:18-3.6-alpine
    platform: linux/amd64
    ports:
      - "5431:5431"
    volumes:
      - ./api.Tests/TestData/test-seed.sql:/docker-entrypoint-initdb.d/test-seed.sql
    environment:
      - POSTGRES_USER=mr-ice-cool
      - POSTGRES_PASSWORD=is-rockin
      - POSTGRES_DB=gascd_data
      - PGPORT=5431