[tools]
dotnet = "10.0.102"  # use your SDK version

[tasks.lint]
description = "Run .NET code formatting and static analysis"
run = """
dotnet restore
dotnet format --verify-no-changes --severity warn
dotnet build --no-restore -warnaserror
"""

[tasks.api]
run = "dotnet run --project api"

[tasks.test]
run = "dotnet test"
