# Docker

# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  # Variable groups
  - group: acr_service_connection
  - group: arm_service_connection
  - group: docker_build_arguments
  # Hardcoded variables
  - name: imageRepository
    value: "dapalpha"
  - name: dockerfilePath
    value: "$(Build.SourcesDirectory)/gascd_app/Dockerfile"
  - name: tag
    value: "$(Build.BuildId)"
  - name: vmImageName
    value: "ubuntu-latest"

# Environment parameters to iterate through
parameters:
  - name: environments
    type: object
    default:
      - name: dev
        environment_name: "Webapp - dev"
        arm_connection: "$(dev_arm_service_connections)"
        acr_connection: "$(dev_acr_connection)"
        acr_name: "$(dev_acr_name)"
      - name: uat
        environment_name: "Webapp - UAT"
        arm_connection: "$(uat_arm_service_connections)"
        acr_connection: "$(uat_acr_connection)"
        acr_name: "$(uat_acr_name)"
      - name: prod
        environment_name: "Webapp - prod"
        arm_connection: "$(prod_arm_service_connections)"
        acr_connection: "$(prod_acr_connection)"
        acr_name: "$(prod_acr_name)"

stages:
  # Run tests once up front
  - stage: Tests
    displayName: "Run jest tests"
    jobs:
      - job: JestTest
        displayName: Run Jests Tests
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: "24.4.1"
          - script: npm ci
            displayName: install dependencies
            workingDirectory: gascd_app
          - script: npm run test -- --reporters=default --reporters=jest-junit --outputFile=gascd_app/junit.xml
            displayName: Run Jest Tests
            workingDirectory: gascd_app
          - task: PublishTestResults@2
            displayName: Publish Test Results
            inputs:
              testResultsFormat: "JUnit"
              searchFolder: "$(Build.SourcesDirectory)"
              testResultsFiles: "gascd_app/junit.xml"
              failTaskOnFailedTests: true
  # Build
  - stage: Build_Image
    displayName: "Build/push Docker image (all environments)"
    condition: succeeded()
    jobs:
      - deployment: Build
        displayName: Build
        environment: "prod"
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                # This step fetches the last 50 commits and all tags.
                # (performance optimization over fetchDepth: 0)
                - checkout: self
                  fetchDepth: 50
                  fetchTags: true

                - script: |
                    NEXT_PUBLIC_FINGERTIPS_GIT_HASH=$(git rev-parse --short HEAD) \
                    NEXT_PUBLIC_FINGERTIPS_GIT_TAG=$(git describe --tags --abbrev=0 --always) \
                    docker build -f $(dockerfilePath) -t $(imageRepository):$(tag) -t $(imageRepository):latest gascd_app/. --build-arg NEXT_PUBLIC_FINGERTIPS_GIT_HASH --build-arg NEXT_PUBLIC_FINGERTIPS_GIT_TAG
                  displayName: Build Image

                - ${{ each environment in parameters.environments}}:
                    - task: Docker@2
                      displayName: Login to ${{environment.acr_connection}} ACR
                      inputs:
                        command: login
                        containerRegistry: ${{environment.acr_connection}}

                    - script: |
                        docker tag $(imageRepository):$(tag) ${{environment.acr_name}}.azurecr.io/$(imageRepository):$(tag)
                        docker tag $(imageRepository):latest ${{environment.acr_name}}.azurecr.io/$(imageRepository):latest
                      displayName: Tag image for ${{environment.acr_name}} ACR

                    - script: |
                        docker push ${{environment.acr_name}}.azurecr.io/$(imageRepository):$(tag)
                        docker push ${{environment.acr_name}}.azurecr.io/$(imageRepository):latest
                      displayName: Push image to ${{environment.acr_name}} ACR
  # Deploy across environments
  - ${{ each environment in parameters.environments}}:
      - stage: Deploy_${{environment.name}}
        displayName: "${{environment.name}}: Deploy to Azure Web App"
        condition: succeeded()
        jobs:
          - deployment: Deploy
            displayName: Deploy
            environment: "${{environment.name}}"
            pool:
              vmImage: "ubuntu-latest"
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: AzureWebAppContainer@1
                      inputs:
                        appType: "webAppLinux"
                        appName: "dapalpha-${{environment.name}}-app"
                        azureSubscription: ${{environment.arm_connection}}
                        containers: "${{environment.acr_name}}.azurecr.io/$(imageRepository):$(tag)"
