using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace api.Migrations
{
    /// <summary>
    /// Six value tables for the September-release metric groups: care home beds per 100,000 under the
    /// 18-64 and 65+ population denominators (GASCD-99/241) and the per-100,000-adults twins of the
    /// primary support reason, expenditure and community care count metrics (GASCD-152).
    /// Same shape as every other MetricTimeSeries table.
    /// </summary>
    public partial class AddPer100kMetricGroupTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Written as idempotent, self-repairing SQL rather than CreateTable, for the same reason as
            // AddDfeMetricTables: the data pipeline may already have created these tables, and its
            // deployment is manual and independent of this one, so neither order can be relied on. A
            // plain CreateTable fails with 42P07 against a table that is already there. This runs
            // unchanged in dev, uat and prod: it creates the table where absent, and where present
            // brings it up to the shape the model expects without touching its rows.
            //
            // It also adopts a pipeline-created table's primary key and indexes under the names EF
            // derives, so that a later migration sees the model it expects rather than a duplicate.
            // EF truncates an identifier longer than 63 characters to 62 plus a tilde; the CASE
            // expressions below reproduce that, because several of these names are over the limit.
            migrationBuilder.Sql(@"
DO $$
DECLARE
    t        text;
    pk_name  text;
    fk_name  text;
    ix_fk    text;
    ix_loc   text;
    existing text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'bedcount_per_hundred_thousand_18_64',
        'bedcount_per_hundred_thousand_65over',
        'num_clients_long_term_support_per100k_adults',
        'expenditure_duration_psr_per100k_adults',
        'expenditure_longterm_support_setting_per100k_adults',
        'num_clients_comm_care_per100k_adults'
    ]
    LOOP
        EXECUTE format('CREATE TABLE IF NOT EXISTS %I (
            id integer GENERATED BY DEFAULT AS IDENTITY,
            loaded_datetime timestamp with time zone NOT NULL,
            start_date date NOT NULL,
            end_date date NOT NULL,
            location_code character varying(15) NOT NULL,
            location_type character varying(25) NOT NULL,
            metric_fk integer NOT NULL,
            time_series numeric[] NOT NULL,
            latest_value numeric
        )', t);

        -- Surrogate key, which a pipeline-created table will not have. Postgres
        -- backfills it for existing rows.
        EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY', t);

        -- EntityBase maps LoadedDateTime to timestamptz; Spark writes naive.
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t
              AND column_name = 'loaded_datetime'
              AND data_type = 'timestamp without time zone'
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN loaded_datetime TYPE timestamptz USING loaded_datetime AT TIME ZONE ''UTC''', t);
        END IF;

        -- The model maps TimeSeries to decimal?[] and LatestValue to decimal?, i.e. numeric.
        -- Spark writes DoubleType as double precision, and Npgsql refuses to read float8 into
        -- decimal, so the query succeeds and then materialisation throws InvalidCastException.
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t
              AND column_name = 'latest_value' AND udt_name = 'float8'
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN latest_value TYPE numeric USING latest_value::numeric', t);
        END IF;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t
              AND column_name = 'time_series' AND udt_name = '_float8'
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN time_series TYPE numeric[] USING time_series::numeric[]', t);
        END IF;

        pk_name := CASE WHEN length('PK_' || t) > 63
                        THEN left('PK_' || t, 62) || '~'
                        ELSE 'PK_' || t END;
        fk_name := CASE WHEN length('FK_' || t || '_metrics_metric_fk') > 63
                        THEN left('FK_' || t || '_metrics_metric_fk', 62) || '~'
                        ELSE 'FK_' || t || '_metrics_metric_fk' END;
        ix_fk   := CASE WHEN length('IX_' || t || '_metric_fk') > 63
                        THEN left('IX_' || t || '_metric_fk', 62) || '~'
                        ELSE 'IX_' || t || '_metric_fk' END;
        ix_loc  := CASE WHEN length('IX_' || t || '_location_code_location_type') > 63
                        THEN left('IX_' || t || '_location_code_location_type', 62) || '~'
                        ELSE 'IX_' || t || '_location_code_location_type' END;

        -- Primary key. A pipeline-created table already has one, under Postgres's default
        -- name, so adopt that rather than trying to add a second.
        SELECT c.conname INTO existing
        FROM pg_constraint c
        JOIN pg_class r ON r.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = r.relnamespace
        WHERE n.nspname = 'public' AND r.relname = t AND c.contype = 'p';

        IF existing IS NULL THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY (id)', t, pk_name);
        ELSIF existing <> pk_name THEN
            EXECUTE format('ALTER TABLE %I RENAME CONSTRAINT %I TO %I', t, existing, pk_name);
        END IF;

        -- Foreign key to metrics. The pipeline's writer has no REFERENCES privilege, so a
        -- pipeline-created table will not have this at all.
        SELECT c.conname INTO existing
        FROM pg_constraint c
        JOIN pg_class r ON r.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = r.relnamespace
        WHERE n.nspname = 'public' AND r.relname = t AND c.contype = 'f';

        IF existing IS NULL THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE',
                           t, fk_name);
        ELSIF existing <> fk_name THEN
            EXECUTE format('ALTER TABLE %I RENAME CONSTRAINT %I TO %I', t, existing, fk_name);
        END IF;

        -- Indexes, matched on the columns they cover rather than on a name, so that a
        -- pipeline-created index is renamed instead of duplicated.
        SELECT indexname INTO existing FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = t AND indexdef LIKE '%(metric_fk)';

        IF existing IS NULL THEN
            EXECUTE format('CREATE INDEX %I ON %I (metric_fk)', ix_fk, t);
        ELSIF existing <> ix_fk THEN
            EXECUTE format('ALTER INDEX %I RENAME TO %I', existing, ix_fk);
        END IF;

        SELECT indexname INTO existing FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = t AND indexdef LIKE '%(location_code, location_type)';

        IF existing IS NULL THEN
            EXECUTE format('CREATE INDEX %I ON %I (location_code, location_type)', ix_loc, t);
        ELSIF existing <> ix_loc THEN
            EXECUTE format('ALTER INDEX %I RENAME TO %I', existing, ix_loc);
        END IF;
    END LOOP;
END $$;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "bedcount_per_hundred_thousand_18_64");

            migrationBuilder.DropTable(
                name: "bedcount_per_hundred_thousand_65over");

            migrationBuilder.DropTable(
                name: "num_clients_long_term_support_per100k_adults");

            migrationBuilder.DropTable(
                name: "expenditure_duration_psr_per100k_adults");

            migrationBuilder.DropTable(
                name: "expenditure_longterm_support_setting_per100k_adults");

            migrationBuilder.DropTable(
                name: "num_clients_comm_care_per100k_adults");
        }
    }
}
