// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(GascdDataContext))]
    [Migration("20260112160005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Data.Models.Metrics.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("data_source");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_type");

                    b.Property<string>("DenominatorDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("denominator_description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("frequency");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<int>("MetricGroupFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_group_fk");

                    b.Property<string>("NumeratorDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("numerator_description");

                    b.HasKey("Id");

                    b.HasIndex("MetricGroupFk");

                    b.ToTable("metrics");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.MetricGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.HasKey("Id");

                    b.ToTable("metric_groups");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Bedcount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("bedcount");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.BedcountPerHundredThousandAdults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("bedcount_per_hundred_thousand_adults");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaEstimatedDiagnosisRate65Over", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("dementia_estimated_diagnosis_rate_65over");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaPrevalence65Over", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("dementia_prevalence_65over");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaQOFPrevalence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("dementia_qof_prevalence");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaRegister65OverPer100k", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("dementia_register_65over_per100k");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.LearningDisabilityPrevalence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("learning_disability_prevalence");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.MedianBedCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("median_bed_count");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.MedianOccupancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("median_occupancy");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.OccupancyRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("occupancy_rates");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc1864", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_18_64");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc65Over", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_65over");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc75Over", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_75over");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc85Over", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_85over");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercGeneralHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_general_health");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercHouseholdOwnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_household_ownership");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercHouseholdsDeprivationDeprived", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_households_deprivation_deprived");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercHouseholdsOnePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_households_one_person");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercPopulationDisability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_population_disability");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercUnpaidCareProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("perc_unpaid_care_provider");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.TotalPopulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("LatestValue")
                        .HasColumnType("numeric")
                        .HasColumnName("latest_value");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("LocationFk")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("location_type");

                    b.Property<int>("MetricFk")
                        .HasColumnType("integer")
                        .HasColumnName("metric_fk");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<decimal[]>("TimeSeries")
                        .IsRequired()
                        .HasColumnType("numeric[]")
                        .HasColumnName("time_series");

                    b.HasKey("Id");

                    b.HasIndex("MetricFk");

                    b.ToTable("total_population");
                });

            modelBuilder.Entity("api.Data.Models.Reference.CareProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("code");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("care_providers");
                });

            modelBuilder.Entity("api.Data.Models.Reference.CareProviderLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<int>("CareProviderFk")
                        .HasColumnType("integer")
                        .HasColumnName("care_provider_fk");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("code");

                    b.Property<int?>("GeoDataFk")
                        .HasColumnType("integer")
                        .HasColumnName("geo_data_fk");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<int>("LocalAuthorityFk")
                        .HasColumnType("integer")
                        .HasColumnName("local_authority_fk");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NominatedIndividual")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nominated_individual");

                    b.HasKey("Id");

                    b.HasIndex("CareProviderFk");

                    b.HasIndex("GeoDataFk");

                    b.HasIndex("LocalAuthorityFk");

                    b.ToTable("care_provider_locations");
                });

            modelBuilder.Entity("api.Data.Models.Reference.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("code");

                    b.Property<int?>("GeoDataFk")
                        .HasColumnType("integer")
                        .HasColumnName("geo_data_fk");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GeoDataFk");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("api.Data.Models.Reference.GeoData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Polygon>("BoundingPolygon")
                        .HasColumnType("geometry (polygon)")
                        .HasColumnName("bounding_polygon");

                    b.Property<Point>("Coordinate")
                        .IsRequired()
                        .HasColumnType("geometry (point)")
                        .HasColumnName("coordinate");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.HasKey("Id");

                    b.ToTable("geo_data");
                });

            modelBuilder.Entity("api.Data.Models.Reference.LocalAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("code");

                    b.Property<int?>("GeoDataFk")
                        .HasColumnType("integer")
                        .HasColumnName("geo_data_fk");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("RegionFk")
                        .HasColumnType("integer")
                        .HasColumnName("region_fk");

                    b.HasKey("Id");

                    b.HasIndex("GeoDataFk");

                    b.HasIndex("RegionFk");

                    b.ToTable("local_authorities");
                });

            modelBuilder.Entity("api.Data.Models.Reference.Postcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayPostcode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("display_postcode");

                    b.Property<int?>("GeoDataFk")
                        .HasColumnType("integer")
                        .HasColumnName("geo_data_fk");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<int>("LocalAuthorityFk")
                        .HasColumnType("integer")
                        .HasColumnName("local_authority_fk");

                    b.HasKey("Id");

                    b.HasIndex("GeoDataFk");

                    b.HasIndex("LocalAuthorityFk");

                    b.ToTable("postcodes");
                });

            modelBuilder.Entity("api.Data.Models.Reference.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("code");

                    b.Property<int>("CountryFk")
                        .HasColumnType("integer")
                        .HasColumnName("country_fk");

                    b.Property<int?>("GeoDataFk")
                        .HasColumnType("integer")
                        .HasColumnName("geo_data_fk");

                    b.Property<DateTime>("LoadedDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryFk");

                    b.HasIndex("GeoDataFk");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.Metric", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.MetricGroup", "MetricGroup")
                        .WithMany()
                        .HasForeignKey("MetricGroupFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricGroup");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Bedcount", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.BedcountPerHundredThousandAdults", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaEstimatedDiagnosisRate65Over", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaPrevalence65Over", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaQOFPrevalence", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.DementiaRegister65OverPer100k", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.LearningDisabilityPrevalence", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.MedianBedCount", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.MedianOccupancy", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.OccupancyRate", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc1864", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc65Over", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc75Over", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.Perc85Over", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercGeneralHealth", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercHouseholdOwnership", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercHouseholdsDeprivationDeprived", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercHouseholdsOnePerson", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercPopulationDisability", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.PercUnpaidCareProvider", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Metrics.TimeSeries.TotalPopulation", b =>
                {
                    b.HasOne("api.Data.Models.Metrics.Metric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("api.Data.Models.Reference.CareProviderLocation", b =>
                {
                    b.HasOne("api.Data.Models.Reference.CareProvider", "CareProvider")
                        .WithMany("CareProviderLocations")
                        .HasForeignKey("CareProviderFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Data.Models.Reference.GeoData", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataFk");

                    b.HasOne("api.Data.Models.Reference.LocalAuthority", "LocalAuthority")
                        .WithMany()
                        .HasForeignKey("LocalAuthorityFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareProvider");

                    b.Navigation("GeoData");

                    b.Navigation("LocalAuthority");
                });

            modelBuilder.Entity("api.Data.Models.Reference.Country", b =>
                {
                    b.HasOne("api.Data.Models.Reference.GeoData", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataFk");

                    b.Navigation("GeoData");
                });

            modelBuilder.Entity("api.Data.Models.Reference.LocalAuthority", b =>
                {
                    b.HasOne("api.Data.Models.Reference.GeoData", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataFk");

                    b.HasOne("api.Data.Models.Reference.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoData");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("api.Data.Models.Reference.Postcode", b =>
                {
                    b.HasOne("api.Data.Models.Reference.GeoData", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataFk");

                    b.HasOne("api.Data.Models.Reference.LocalAuthority", "LocalAuthority")
                        .WithMany()
                        .HasForeignKey("LocalAuthorityFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoData");

                    b.Navigation("LocalAuthority");
                });

            modelBuilder.Entity("api.Data.Models.Reference.Region", b =>
                {
                    b.HasOne("api.Data.Models.Reference.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Data.Models.Reference.GeoData", "GeoData")
                        .WithMany()
                        .HasForeignKey("GeoDataFk");

                    b.Navigation("Country");

                    b.Navigation("GeoData");
                });

            modelBuilder.Entity("api.Data.Models.Reference.CareProvider", b =>
                {
                    b.Navigation("CareProviderLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
