// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using api.Data;

#nullable disable

namespace api.Migrations
{
    // Hand-authored alongside the migration (no .NET SDK on the authoring machine, so `dotnet ef migrations add`
    // could not run). The target model lives in GascdDataContextModelSnapshot, which is updated in the same
    // change; regenerate this file with `dotnet ef migrations add AddPer100kMetricGroupTables --project api`
    // (after deleting both files) if a full BuildTargetModel is preferred.
    [DbContext(typeof(GascdDataContext))]
    [Migration("20260922120000_AddPer100kMetricGroupTables")]
    partial class AddPer100kMetricGroupTables
    {
    }
}
