using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    /// <inheritdoc />
    public partial class AddDfeMetricTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Written as idempotent, self-repairing SQL rather than CreateTable
            // because the data pipeline may already have created these tables,
            // in a Spark shape that does not match the model (no surrogate key,
            // naive timestamps). A plain CreateTable fails against those with
            // 42P07, and the only recoveries are dropping the table (loses the
            // loaded data) or hand-written SQL per environment (does not
            // promote). This runs unchanged in dev, tst and prd: it creates the
            // table where absent, and brings an existing one up to the shape the
            // model expects without touching its rows.
            migrationBuilder.Sql(@"
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'num_sen_support_14plus', 'perc_sen_support_14plus', 'num_ehcp_14plus',
        'num_children_in_need', 'cin_per_10000_children', 'num_cin_transfer_asc'
    ]
    LOOP
        EXECUTE format('CREATE TABLE IF NOT EXISTS %I (
            id integer GENERATED BY DEFAULT AS IDENTITY,
            loaded_datetime timestamp with time zone NOT NULL,
            start_date date NOT NULL,
            end_date date NOT NULL,
            location_code character varying(15) NOT NULL,
            location_type character varying(25) NOT NULL,
            metric_fk integer NOT NULL,
            time_series numeric[] NOT NULL,
            latest_value numeric
        )', t);

        -- Surrogate key, which a pipeline-created table will not have. Postgres
        -- backfills it for existing rows.
        EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY', t);

        -- EntityBase maps LoadedDateTime to timestamptz; Spark writes naive.
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t
              AND column_name = 'loaded_datetime'
              AND data_type = 'timestamp without time zone'
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN loaded_datetime TYPE timestamptz USING loaded_datetime AT TIME ZONE ''UTC''', t);
        END IF;

        -- The model maps TimeSeries to decimal?[] and LatestValue to decimal?,
        -- i.e. numeric. Spark writes DoubleType as double precision, and Npgsql
        -- refuses to read float8 into decimal, so the query succeeds and then
        -- materialisation throws InvalidCastException.
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t
              AND column_name = 'latest_value' AND udt_name = 'float8'
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN latest_value TYPE numeric USING latest_value::numeric', t);
        END IF;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = t
              AND column_name = 'time_series' AND udt_name = '_float8'
        ) THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN time_series TYPE numeric[] USING time_series::numeric[]', t);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PK_' || t) THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY (id)', t, 'PK_' || t);
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_' || t || '_metrics_metric_fk') THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (metric_fk) REFERENCES metrics (id) ON DELETE CASCADE',
                           t, 'FK_' || t || '_metrics_metric_fk');
        END IF;

        EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (location_code, location_type)',
                       'IX_' || t || '_location_code_location_type', t);
        EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (metric_fk)', 'IX_' || t || '_metric_fk', t);
    END LOOP;
END $$;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "cin_per_10000_children");

            migrationBuilder.DropTable(
                name: "num_children_in_need");

            migrationBuilder.DropTable(
                name: "num_cin_transfer_asc");

            migrationBuilder.DropTable(
                name: "num_ehcp_14plus");

            migrationBuilder.DropTable(
                name: "num_sen_support_14plus");

            migrationBuilder.DropTable(
                name: "perc_sen_support_14plus");
        }
    }
}
