#!/usr/bin/env -S uv run --script
import os, sys

def generate_bootstrap_sql(sqlproj_path: str):
    """
    Generates a single SQL file to bootstrap a database from a SQL Server .sqlproj directory.

    The script identifies direct subdirectories as schemas, creates CREATE SCHEMA commands,
    and then concatenates all .sql files found within a 'Tables' subdirectory inside each schema.
    It also adds CREATE DATABASE and USE statements based on the .sqlproj file name.

    Args:
        sqlproj_path (str): The path to the root of the .sqlproj directory.
        output_file_name (str): The name of the output SQL file.
    """
    if not os.path.isdir(sqlproj_path):
        print(f"Error: The provided path '{sqlproj_path}' is not a valid directory.")
        return

    bootstrap_sql_content = []
    schemas_to_create = []
    sql_files_content = []
    database_name = None

    # Find the .sqlproj file to determine the database name
    for file_name in os.listdir(sqlproj_path):
        if file_name.lower().endswith(".sqlproj"):
            database_name = os.path.splitext(file_name)[0] # Get name without extension
            break

    if database_name is None:
        print(f"Error: No .sqlproj file found in '{sqlproj_path}'. Cannot determine database name.")
        return

    # Add a header comment to the output file
    bootstrap_sql_content.append("-- This SQL script was generated to bootstrap a database from a .sqlproj directory.")
    bootstrap_sql_content.append("-- Generated by the SQL Project Bootstrap Script.\n")

    # Add CREATE DATABASE and USE statements
    bootstrap_sql_content.append(f"IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'{database_name}')")
    bootstrap_sql_content.append(f"BEGIN")
    bootstrap_sql_content.append(f"    CREATE DATABASE [{database_name}];")
    bootstrap_sql_content.append(f"END;")
    bootstrap_sql_content.append(f"GO\n")
    bootstrap_sql_content.append(f"USE [{database_name}];")
    bootstrap_sql_content.append(f"GO\n")

    # Get all direct entries in the sqlproj_path
    for entry_name in os.listdir(sqlproj_path):
        entry_path = os.path.join(sqlproj_path, entry_name)

        # Only process direct subdirectories as potential schemas
        if os.path.isdir(entry_path):
            # Skip common build/version control directories
            if entry_name.startswith(('.', 'bin', 'obj', '.vs')):
                continue

            # Look for a "Tables" subdirectory within the current schema directory
            tables_dir_path = os.path.join(entry_path, "Tables")
            if os.path.isdir(tables_dir_path):
                # Make the schema
                schema_name = entry_name
                schemas_to_create.append(f"IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'{schema_name}')\nBEGIN\n    EXEC('CREATE SCHEMA [{schema_name}]');\nEND;")

                # Collect all .sql files from the "Tables" directory
                for file_name in sorted(os.listdir(tables_dir_path)): # Sort files for consistent order
                    if file_name.lower().endswith(".sql"):
                        file_path = os.path.join(tables_dir_path, file_name)
                        try:
                            with open(file_path, 'r', encoding='utf-8') as f:
                                # Relative path for comment
                                relative_file_path = os.path.join(schema_name, "Tables", file_name)
                                sql_files_content.append(f"-- File: {relative_file_path}")
                                sql_files_content.append(f.read())
                                sql_files_content.append("\nGO\n") # Add GO separator for SQL Server batches
                        except Exception as e:
                            print(f"Warning: Could not read file '{file_path}'. Skipping. Error: {e}")


    # Combine the content: Schemas first, then SQL objects
    if schemas_to_create:
        bootstrap_sql_content.append("-- Schema Creation")
        bootstrap_sql_content.extend(schemas_to_create)
        bootstrap_sql_content.append("\nGO\n")

    if sql_files_content:
        bootstrap_sql_content.append("-- Database Object Creation")
        bootstrap_sql_content.extend(sql_files_content)

    output_file_name = f"{database_name}_bootstrap.sql"

    # Write the combined content to the output file
    output_file_path = os.path.join(os.getcwd(), output_file_name)
    try:
        with open(output_file_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(bootstrap_sql_content))
        print(f"Successfully generated '{output_file_name}' at '{output_file_path}'")
    except Exception as e:
        print(f"Error: Could not write to output file '{output_file_path}'. Error: {e}")

if __name__ == "__main__":
    try:
        sql_project_directory = sys.argv[1]
    except IndexError:
        print(f"Usage: {sys.argv[0]} /path/to/sqlproj")
        sys.exit(1)
    generate_bootstrap_sql(sql_project_directory)
