/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/geo/postcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get geo details for a postcode */
        get: {
            parameters: {
                query: {
                    /** @description sanitised postcode (no whitespace) fixed case */
                    postcode: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Postcode object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Postcode"];
                    };
                };
                /** @description Postcode doesn't meet validation requirements: 5-7 chars inclusive */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No details found for postcode */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisation/care_provider/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the care provider locations linked to a care provider organisation.
         * @description Retrieves the list of Care Provider (CP) locations that the currently linked to a Care Provider Organisation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier for the care provider. */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of care provider locations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The unique identifier for this Care Provider */
                            code?: string;
                            /** @description Display name of the Care Provider */
                            display_name?: string;
                            /** @description A list of Care provider locations belonging to this Care Provider */
                            locations?: {
                                /** @description The unique identifier of the location. */
                                location_code?: string;
                                /** @description The display name of the location. */
                                location_name?: string;
                                /** @description The name of the care provide location's Local Authority. */
                                la_name?: string;
                                /** @description The code of the care provide location's Local Authority. */
                                la_code?: string;
                                /** @description The category of the location. */
                                location_category?: string;
                                /** @description The address of the location. */
                                address?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric_locations/cp_locations/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a care provider location
         * @description Retrieves detailed information for a single care provider location by its code.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Whether to include parent location information. */
                    include_parents?: boolean;
                };
                header?: never;
                path: {
                    /** @description The unique identifier for the care provider. */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed information for the requested location. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CareProviderLocation"];
                    };
                };
                /** @description Care provider location not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric_locations/districts/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a district
         * @description Retrieves detailed information for a district by its code. TBC This endpoint may not be required
         */
        get: {
            parameters: {
                query?: {
                    /** @description Whether to include parent location information. */
                    include_parents?: boolean;
                };
                header?: never;
                path: {
                    /** @description The unique identifier for the district. */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed information for the requested location. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["District"];
                    };
                };
                /** @description District not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric_locations/local_authorities/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a local authority
         * @description Retrieves detailed information for a local authority by its code.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Whether to include parent location information. */
                    include_parents?: boolean;
                };
                header?: never;
                path: {
                    /** @description The unique identifier for the local authority. */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed information for the requested location. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LocalAuthority"];
                    };
                };
                /** @description Local authority not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric_locations/regions/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a region
         * @description Retrieves detailed information for a region by its code.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier for the region. */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed information for the requested location. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Region"];
                    };
                };
                /** @description Region not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric_locations/countries/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a country
         * @description Retrieves detailed information for a country by its code.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier for the country. */
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed information for the requested location. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Country"];
                    };
                };
                /** @description Country not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metric_filters/{metric_group_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available filters for a group of metrics
         * @description Retrieves the available filter options for a metric group.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier for the metric group. */
                    metric_group_code: components["parameters"]["MetricGroupCode"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of available filter options. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricFilters"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metric_code}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metadata for a specific metric
         * @description Retrieves all metadata for a single metric, including its name, numerator, and denominator definitions.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier for the metric. */
                    metric_code: components["parameters"]["MetricCode"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The metadata for the requested metric. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricMetadata"];
                    };
                };
                /** @description Metric not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{metric_code}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get time-series or most recent data for a single metric
         * @description Retrieves data points for a single specified metric across one or more locations. Omit the time_series parameter to get the most recent data point. Include time_series=true to get the time-series.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Boolean whether to return whole time series. If false or omitted, only the most recent data point is returned. */
                    time_series?: boolean;
                };
                header?: never;
                path: {
                    /** @description The unique identifier for the metric. */
                    metric_code: components["parameters"]["MetricCode"];
                };
                cookie?: never;
            };
            /** @description A list of locations to retrieve data for. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
            responses: {
                /** @description A list of matching metric series for the specified metric. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricSeries"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Represents a care provider location */
        CareProviderLocation: {
            /** @description Unique identifier for the care provider location. */
            code?: string;
            /** @description Display name of the care provider location. */
            display_name?: string;
            /** @description Address of the care provider location. */
            address?: string;
            geo_data?: components["schemas"]["GeoData"];
            /** @description The parent provider code. */
            provider_code?: string;
            /** @description The parent provider name. */
            provider_name?: string;
            /** @description The category of the location. */
            location_category?: string;
            /** @description The nominated individual for the care provider location. */
            nominated_individual?: string;
            /** @description The associated local authority ID. */
            local_authority_code?: string | null;
            /** @description The associated local authority name. */
            local_authority_name?: string | null;
            /** @description The associated region code. */
            region_code?: string | null;
            /** @description The associated region name. */
            region_name?: string | null;
            /** @description The associated country code. */
            country_code?: string | null;
            /** @description The associated country name. */
            country_name?: string | null;
        };
        /** @description Represents a district */
        District: {
            /** @description Unique identifier for the district. */
            code?: string;
            /** @description Display name of the district. */
            display_name?: string;
            geo_data?: components["schemas"]["GeoData"];
            /** @description The associated local authority code. */
            local_authority_code?: string;
            /** @description The associated region code. */
            region_code?: string | null;
            /** @description The associated country code. */
            country_code?: string | null;
        };
        /** @description Represents a local authority */
        LocalAuthority: {
            /** @description Unique identifier for the local authority. */
            code?: string;
            /** @description Display name of the local authority. */
            display_name?: string;
            geo_data?: components["schemas"]["GeoData"];
            /** @description The associated region code. */
            region_code?: string | null;
            /** @description The associated region name. */
            region_name?: string | null;
            /** @description The associated country code. */
            country_code?: string | null;
            /** @description The associated country name. */
            country_name?: string | null;
        };
        /** @description Represents a region */
        Region: {
            /** @description Unique identifier for the region. */
            code?: string;
            /** @description Display name of the region. */
            display_name?: string;
            geo_data?: components["schemas"]["GeoData"];
            /** @description The associated country code. */
            country_code?: string;
            /** @description The associated country name. */
            country_name?: string;
            /** @description A list of local authorities within this region */
            local_authorities?: {
                /** @description The local authority name. */
                la_name?: string;
                /** @description The local authority code. */
                la_code?: string;
            }[];
        };
        /** @description Represents a country */
        Country: {
            /** @description Unique identifier for the country. */
            code?: string;
            /** @description Display name of the country. */
            display_name?: string;
            geo_data?: components["schemas"]["GeoData"];
        };
        /** @description Geo details for postcode */
        Postcode: {
            /** @description Clean postcode with no whitespace used to search DB */
            sanitised_postcode?: string;
            /** @description Properly formatted postcode for display */
            display_postcode?: string;
            geo_data?: components["schemas"]["GeoData"];
            /** @description Local authority code. */
            la_code?: string;
            /** @description Local authority name. */
            la_name?: string;
        };
        /** @description Geographical data for a location. */
        GeoData: {
            /** @description Latitude of the centre point of the location. */
            latitude?: number;
            /** @description Longitude of the centre point of the location. */
            longitude?: number;
            polygon?: components["schemas"]["Coordinate"][];
        };
        /** @description Pair of coordinates */
        Coordinate: {
            /** @description Latitude of the location. */
            latitude?: number;
            /** @description Longitude of the location. */
            longitude?: number;
        };
        /** @description A location type and code pair. */
        Location: {
            /**
             * @description The locations unique code.
             * @example 1-123456789
             */
            location_code?: string;
            /**
             * @description The type of this location.
             * @default la
             * @enum {string}
             */
            location_type: "LA" | "National" | "Regional" | "CareProviderLocation";
        };
        /** @description Defines the properties and context of a metric. */
        MetricMetadata: {
            /** @description The unique identifier for the metric. */
            metric_code?: string;
            /** @description The display name for the metric. */
            metric_name?: string;
            /** @description A user-friendly name for the metric filter. */
            filter_type?: string;
            /** @description The format of the metric's data, e.g., 'Percentage', 'Currency'. */
            data_type?: string;
            /** @description The source of the data for this metric. */
            data_source?: string;
            /** @description A description of the numerator. */
            numerator?: string;
            /** @description A description of the denominator. */
            denominator?: string;
        };
        /** @description An available filter for a metric, such as bed type. */
        MetricFilters: {
            /**
             * @description The specific metric group code this filter applies to.
             * @example bedcount_per_100000_adults
             */
            metric_group_code?: string;
            /**
             * @description A user-friendly name for the metric group.
             * @example General nursing
             */
            metric_group_display_name?: string;
            /** @description A list of Metric filters belonging to this Metric Group */
            metric_filters?: {
                /**
                 * @description The specific metric code this filter applies to.
                 * @example bedcount_per_100000_adults_total_general_nursing
                 */
                metric_code?: string;
                /** @description A user-friendly name for the metric filter. */
                filter_type?: string;
            }[];
        };
        /** @description A series of data points at a specific time and location specified in the call for the metric. */
        MetricSeries: {
            /** @description The unique identifier for the metric. */
            metric_code?: string;
            /** @description The unique identifier for the location. */
            location_code?: string;
            /** @description The type of the location. */
            location_type?: string;
            /**
             * Format: date
             * @description The start date of the metric series.
             */
            series_start_date?: string;
            /**
             * Format: date
             * @description The end date of the metric series.
             */
            series_end_date?: string;
            /**
             * @description The frequency of data points for the time series.
             * @default latest
             * @enum {string}
             */
            series_frequency: "latest" | "daily" | "monthly" | "yearly";
            /** @description The calculated data points at the specified frequency. If frequency is 'latest' this array will have one data point */
            values?: number[];
        };
    };
    responses: never;
    parameters: {
        /** @description The unique identifier for the metric. */
        MetricCode: string;
        /** @description The unique identifier for the metric group. */
        MetricGroupCode: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
