/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/geo/postcode': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get geo details for a postcode */
    get: {
      parameters: {
        query: {
          /** @description sanitised postcode (no whitespace) fixed case */
          postcode: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Postcode object */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Postcode'];
          };
        };
        /** @description Postcode doesn't meet validation requirements: 5-7 chars inclusive */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No details found for postcode */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organisation/care_provider/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the care provider locations linked to a care provider organisation.
     * @description Retrieves the list of Care Provider (CP) locations that the currently linked to a Care Provider Organisation.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The unique identifier for the care provider. */
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of care provider locations */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description The unique ID of the location. */
              location_id?: string;
              /** @description The display name of the location. */
              location_name?: string;
            }[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metric_locations/cp_locations/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a care provider location
     * @description Retrieves detailed information for a single care provider location by its ID.
     */
    get: {
      parameters: {
        query?: {
          /** @description Whether to include parent location information. */
          includeParents?: boolean;
        };
        header?: never;
        path: {
          /** @description The unique identifier for the care provider. */
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Detailed information for the requested location. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CareProviderLocation'];
          };
        };
        /** @description Care provider location not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metric_locations/districts/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a district
     * @description Retrieves detailed information for a district by its ID. TBC This endpoint may not be required
     */
    get: {
      parameters: {
        query?: {
          /** @description Whether to include parent location information. */
          includeParents?: boolean;
        };
        header?: never;
        path: {
          /** @description The unique identifier for the district. */
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Detailed information for the requested location. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['District'];
          };
        };
        /** @description District not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metric_locations/local_authorities/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a local authority
     * @description Retrieves detailed information for a local authority by its ID.
     */
    get: {
      parameters: {
        query?: {
          /** @description Whether to include parent location information. */
          includeParents?: boolean;
        };
        header?: never;
        path: {
          /** @description The unique identifier for the local authority. */
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Detailed information for the requested location. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LocalAuthority'];
          };
        };
        /** @description Local authority not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metric_locations/regions/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a region
     * @description Retrieves detailed information for a region by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The unique identifier for the region. */
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Detailed information for the requested location. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Region'];
          };
        };
        /** @description Region not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metric_locations/countries/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a country
     * @description Retrieves detailed information for a country by its ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The unique identifier for the country. */
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Detailed information for the requested location. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Country'];
          };
        };
        /** @description Country not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metric_filters/{metricGroupId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get available filters for a group of metrics
     * @description Retrieves the available filter options for a metric group.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The unique identifier for the metric group. */
          metricGroupId: components['parameters']['MetricGroupId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of available filter options. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MetricFilter'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics/{metricId}/metadata': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get metadata for a specific metric
     * @description Retrieves all metadata for a single metric, including its name, numerator, and denominator definitions.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The unique identifier for the metric. */
          metricId: components['parameters']['MetricId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The metadata for the requested metric. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MetricMetadata'];
          };
        };
        /** @description Metric not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics/{metricId}/data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get time-series or most recent data for a single metric
     * @description Retrieves data points for a single specified metric across one or more locations. Omit date parameters to get the most recent data point. Provide a startDate to get a time-series.
     */
    get: {
      parameters: {
        query: {
          /** @description Comma-separated list of location IDs to retrieve data for. */
          locationId: string[];
          /** @description The start date for the time series (YYYY-MM-DD). If omitted, only the most recent data point is returned. */
          startDate?: string;
          /** @description The end date for the time series (YYYY-MM-DD). Defaults to the current date if startDate is provided. */
          endDate?: string;
          /** @description The frequency of data points for the time series. To get just the most recent data point, use 'latest' */
          frequency?: 'latest' | 'daily' | 'monthly' | 'yearly';
        };
        header?: never;
        path: {
          /** @description The unique identifier for the metric. */
          metricId: components['parameters']['MetricId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of matching metric series for the specified metric. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MetricSeries'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Represents a care provider location */
    CareProviderLocation: {
      /** @description Unique identifier for the care provider location. */
      id?: string;
      /** @description Display name of the care provider location. */
      display_name?: string;
      /** @description Address of the care provider location. */
      address?: string;
      /** @description Geographical data for the care provider location. */
      geo_data?: {
        /** @description Latitude of the location. */
        latitude?: number;
        /** @description Longitude of the location. */
        longitude?: number;
        /** @description Bounding box coordinates. */
        bbox?: number[];
      };
      /** @description The parent provider ID. */
      provider_id?: string;
      /** @description The parent provider name. */
      provider_name?: string;
      /** @description The nominated individual for the care provider location. */
      nominated_individual?: string;
      /** @description The associated local authority ID. */
      local_authority_id?: string;
      /** @description The associated region ID. */
      region_id?: string | null;
      /** @description The associated country ID. */
      country_id?: string | null;
    };
    /** @description Represents a district */
    District: {
      /** @description Unique identifier for the district. */
      id?: string;
      /** @description Display name of the district. */
      display_name?: string;
      /** @description Geographical data for the district. */
      geo_data?: {
        /** @description Latitude of the centre point of the district. */
        latitude?: number;
        /** @description Longitude of the centre point of the district. */
        longitude?: number;
        /** @description Bounding box coordinates. */
        bbox?: number[];
      };
      /** @description The associated local authority ID. */
      local_authority_id?: string;
      /** @description The associated region ID. */
      region_id?: string | null;
      /** @description The associated country ID. */
      country_id?: string | null;
    };
    /** @description Represents a local authority */
    LocalAuthority: {
      /** @description Unique identifier for the local authority. */
      id?: string;
      /** @description Display name of the local authority. */
      display_name?: string;
      /** @description Geographical data for the local authority. */
      geo_data?: {
        /** @description Latitude of the centre point of the local authority. */
        latitude?: number;
        /** @description Longitude of the centre point of the local authority. */
        longitude?: number;
        /** @description Bounding box coordinates. */
        bbox?: number[];
      };
      /** @description The associated region ID. */
      region_id?: string;
      /** @description The associated country ID. */
      country_id?: string | null;
    };
    /** @description Represents a region */
    Region: {
      /** @description Unique identifier for the region. */
      id?: string;
      /** @description Display name of the region. */
      display_name?: string;
      /** @description Geographical data for the region. */
      geo_data?: {
        /** @description Latitude of the centre point of the region. */
        latitude?: number;
        /** @description Longitude of the centre point of the region. */
        longitude?: number;
        /** @description Bounding box coordinates. */
        bbox?: number[];
      };
      /** @description The associated country ID. */
      country_id?: string;
    };
    /** @description Represents a country */
    Country: {
      /** @description Unique identifier for the country. */
      id?: string;
      /** @description Display name of the country. */
      display_name?: string;
      /** @description Geographical data for the country. */
      geo_data?: {
        /** @description Latitude of the centre point of the country. */
        latitude?: number;
        /** @description Longitude of the centre point of the country. */
        longitude?: number;
        /** @description Bounding box coordinates. */
        bbox?: number[];
      };
    };
    /** @description Geo details for postcode */
    Postcode: {
      /** @description Clean postcode with no whitespace used to seach DB */
      sanitised_postcode?: string;
      /** @description Properly formatted postcode for display */
      display_postcode?: string;
      /** @description The postcode latitude. */
      latitude?: number;
      /** @description The postcode longitude. */
      longitude?: number;
      /** @description Local authority code. */
      la_code?: string;
      /** @description Local authority name. */
      la_name?: string;
    };
    /** @description Defines the properties and context of a metric. */
    MetricMetadata: {
      /** @description The unique identifier for the metric. */
      metric_id?: string;
      /** @description The display name for the metric. */
      metric_name?: string;
      /** @description The format of the metric's data, e.g., 'Percentage', 'Currency'. */
      data_type?: string;
      /** @description The source of the data for this metric. */
      data_source?: string;
      /** @description A description of the numerator. */
      numerator?: string;
      /** @description A description of the denominator. */
      denominator?: string;
    };
    /** @description An available filter for a metric, such as bed type. */
    MetricFilter: {
      /**
       * @description The specific metric group ID this filter applies to.
       * @example bedcount_per_100000_adults
       */
      metric_group_id?: string;
      /**
       * @description The specific metric ID this filter applies to.
       * @example bedcount_per_100000_adults_total_general_nursing
       */
      metric_id?: string;
      /**
       * @description A user-friendly name for the filter value.
       * @example General nursing
       */
      display_name?: string;
    };
    /** @description A series of data points at a specific time and location specified in the call for the metric. */
    MetricSeries: {
      /** @description The unique identifier for the metric. */
      metric_id?: string;
      /** @description The unique identifier for the location. */
      location_id?: string;
      /**
       * Format: date
       * @description The start date of the metric series.
       */
      series_start_date?: string;
      /**
       * @description The frequency of data points for the time series.
       * @default latest
       * @enum {string}
       */
      series_frequency: 'latest' | 'daily' | 'monthly' | 'yearly';
      /** @description The calculated data points at the specified frequency. If frequency is 'latest' this array will have one data point */
      values?: number[];
    };
  };
  responses: never;
  parameters: {
    /** @description The unique identifier for the metric. */
    MetricId: string;
    /** @description The unique identifier for the metric group. */
    MetricGroupId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
