METRIC_METADATA = {
    "occupancy_rate_total": {
        "group_id": "occupancy_rate",
        "group_name": "Percentage of adult social care beds occupied",
        "description": "The percentage of occupied beds recorded by care providers across social care compared to the number of beds available.",
        "numerator_description": "Number of occupied beds",
        "denominator_description": "Number of beds recorded by care providers",
        "data_source": "Capacity Tracker",
        "filter_bedtype": "All bed types",
        "metric_data_type": "Percentage",
        "methodology": None,
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "All bed types",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_total": {
        "group_id": "bedcount",
        "group_name": "Adult social care beds in care provider location",
        "description": "The total number of beds recorded by the care providers across health and adult social care",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": None,
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "All bed types",
        "metric_data_type": "Number",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "median_bed_count_total": {
        "group_id": "median_bed_count",
        "group_name": "Median number of adult social care beds provided by a single care provider location",
        "description": "The average (median) number of adult social care beds beds recorded by a care provider location",
        "numerator_description": None,
        "denominator_description": None,
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "All bed types",
        "metric_data_type": "Number",
        "methodology": None,
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Derived metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "median_occupancy_total": {
        "group_id": "median_occupancy",
        "group_name": "Median occupancy percentage of adult social care beds provided by a care provider location",
        "description": "The average (median) percentage of occupied beds recorded by care providers across social care compared to the number of beds avilable.",
        "numerator_description": "Number of occupied beds",
        "denominator_description": "Number of beds recorded by care providers",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "All bed types",
        "metric_data_type": "Percentage",
        "methodology": None,
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Derived metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_general_nursing": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "General nursing",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_learning_disability_residential": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Learning disability residential",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_mental_health_nursing": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Mental health nursing",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_mental_health_residential": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Mental health residential",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_transitional": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Transitional",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_ypd_young_physically_disabled": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Young physically disabled",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "total_population": {
        "group_id": "total_population",
        "group_name": "Total population",
        "description": "The total population",
        "numerator_description": None,
        "denominator_description": None,
        "data_source": "ONS",
        "filter_bedtype": None,
        "metric_data_type": "Number",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "perc_18_64": {
        "group_id": "perc_18_64",
        "group_name": "Percentage of population between the age of 18 and 64",
        "description": "The percentage of individuals that are between 18 and 64 years in age compared to the total population.",
        "numerator_description": "Population between the age of 18 and 64",
        "denominator_description": "Total population",
        "data_source": "ONS",
        "filter_bedtype": None,
        "metric_data_type": "Percentage",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "perc_65over": {
        "group_id": "perc_65over",
        "group_name": "Percentage of population over the age of 65",
        "description": "The percentage of individuals over the age of 65 years compared to the total population",
        "numerator_description": "Population over the age of 65",
        "denominator_description": "Total population",
        "data_source": "ONS",
        "filter_bedtype": None,
        "metric_data_type": "Percentage",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "perc_75over": {
        "group_id": "perc_75over",
        "group_name": "Percentage of population over the age of 75",
        "description": "The percentage of individuals over the age of 75 years compared to the total population",
        "numerator_description": "Population over the age of 75",
        "denominator_description": "Total population",
        "data_source": "ONS",
        "filter_bedtype": None,
        "metric_data_type": "Percentage",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_dementia_nursing": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Dementia nursing",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_general_residential": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "General residential",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_dementia_residential": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Dementia residential",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "bedcount_per_100000_adults_total_learning_disability_nursing": {
        "group_id": "bedcount_per_100000_adults",
        "group_name": "Adult social care beds per 100,000 adult population",
        "description": "The total number of beds recorded by care providers across health and adult social care, adjusted to a rate of 100,000 adults in the local authority population.",
        "numerator_description": "Number of beds recorded by care providers",
        "denominator_description": "Adult population",
        "data_source": "Capacity Tracker, ONS",
        "filter_bedtype": "Learning disability nursing",
        "metric_data_type": "Number",
        "methodology": "The total number of beds is the number of beds reported by care providers, including those in use and those available for new admissions. Total beds includes mental health, learning disabilities, and end-of-life care beds in residential and nursing care homes.The data covers both self-funded and local authority-funded beds. Care providers update this information daily or whenever changes occur using the Capacity Tracker tool. They report how many beds are available and occupied in care settings such as nursing homes, residential care, and community care. The data is grouped by local areas, regions, and nationally so it is easier to compare.",
        "limitations": "Capacity Tracker data is self-reported by care providers, who update it at different times throughout the month. This means the data does not provide a snapshot of all providers at the same point in time. Instead, it represents the most recent information available from each provider when the data was retrieved.",
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "perc_85over": {
        "group_id": "perc_85over",
        "group_name": "Percentage of population over the age of 85",
        "description": "The percentage of individuals over the age of 85 years compared to the total population",
        "numerator_description": "Population over the age of 85",
        "denominator_description": "Total population",
        "data_source": "ONS",
        "filter_bedtype": None,
        "metric_data_type": "Percentage",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "perc_population_disability_disabled_total": {
        "group_id": "perc_population_disability",
        "group_name": "Percentage of disabled adult population",
        "description": "The percentage of individuals who report having any physical or menthal health conditions of illnesses lasting or expected to last 12 months or more.",
        "numerator_description": "Adults reporting any physical or mental health condition or illnesses lasting or expected to last 12 months or more",
        "denominator_description": "Total population",
        "data_source": "ONS",
        "filter_bedtype": None,
        "metric_data_type": "Percentage",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    },
    "dementia_register_65over_per100k": {
        "group_id": "dementia_register_65over_per100k",
        "group_name": "Registered dementia patients over the age of 65 years per 100,000 population aged 65 and over",
        "description": "The percentage of indidividuals aged over the age of 65 that are registered dementia patients.",
        "numerator_description": "Number of registered dementia patients over the age of 65",
        "denominator_description": "Total population",
        "data_source": "NHS England",
        "filter_bedtype": None,
        "metric_data_type": "Number",
        "methodology": None,
        "limitations": None,
        "access_category": None,
        "metric_type": "Metric",
        "is_live": 1,
        "deep_dive": 0
    }
}