# Local development docker compose for the frontend
# (only used for development/testing at the moment)
services:
    app:
        container_name: gascd_frontend
        image: gascd_frontend_image
        build:
            context: .
            args:
                - NEXT_PUBLIC_GASCD_GIT_HASH=${NEXT_PUBLIC_GASCD_GIT_HASH}
                - NEXT_PUBLIC_GASCD_GIT_TAG=${NEXT_PUBLIC_GASCD_GIT_TAG}
        ports:
            - 3000:80
        env_file:
            - .env
        environment:
            - PORT=80
            # Override hosts if running in docker
            - USER_DB_SERVER=host.docker.internal
            - DB_SERVER=host.docker.internal
    userdb:
        container_name: gascd_frontend_userdb
        image: gascd_userdb_image
        build:
            context: ./TestData/testing_userdb
            dockerfile: Dockerfile_userdb
        env_file: 
            - .env
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "${USER_DB_PASSWORD}"
            MSSQL_PID: "Evaluation"
            DB_NAME: "${USER_DATABASE}"
        ports:
            - "1444:1433"
        volumes:
            - gascd_userdb_data:/var/opt/mssql
        restart: always 

    onelogin_simulator:
        container_name: gascd_frontend_onelogin_simulator
        image: ghcr.io/govuk-one-login/simulator:latest
        environment:
            PORT: 4000
            SIMULATOR_URL: "http://localhost:4000"
            CLIENT_ID: ${ONELOGIN_CLIENT_ID}
            REDIRECT_URLS: "http://localhost:3000/api/auth/oauth2/callback/govuk-one-login"
            IDENTITY_VERIFICATION_SUPPORTED: "false"
            TOKEN_AUTH_METHOD: "client_secret_post"
            CLIENT_SECRET_HASH: "${ONELOGIN_CLIENT_SECRET_HASH_ESCAPED}"
            CLIENT_LOCS: "P0"
            INTERACTIVE_MODE: "true"
            TEST_USER_EMAIL: "${LOCAL_AUTH_EMAIL}"
        ports:
            - "4000:4000"
        restart: always 

# Define named volumes so that data persists
volumes:
  gascd_userdb_data:
    driver: local

