openapi: 3.0.3
info:
  title: "Get Adult Social Care API"
  description: "A RESTful API for accessing health and care provider metric data, metadata, and insights."
  version: "0.0.1"
servers:
  - url: "http://gascd.internal"

security:
  - ApiKey: []

paths:
  /api/geo/postcode:
    get:
      summary: "Get geo details for a postcode"
      parameters:
        - name: postcode
          description: "sanitised postcode (no whitespace) fixed case"
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Postcode object"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postcode'
        '400':
          description: "Postcode doesn't meet validation requirements: 5-7 chars inclusive"
        '404':
          description: "No details found for postcode"

  /api/organisation/care_provider/{code}:
    get:
      summary: "Get the care provider locations linked to a care provider organisation."
      description: "Retrieves the list of Care Provider (CP) locations that the currently linked to a Care Provider Organisation."
      parameters:
        - name: code
          in: path
          required: true
          description: "The unique identifier for the care provider."
          schema:
            type: string
            example: "1-12345678"
      responses:
        '200':
          description: "A list of care provider locations"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: "The unique identifier for this Care Provider"
                  display_name:
                    type: string
                    description: "Display name of the Care Provider"
                  locations:
                    type: array
                    description: "A list of Care provider locations belonging to this Care Provider"
                    items:
                      type: object
                      properties:
                        location_code:
                          type: string
                          description: "The unique identifier of the location."
                        location_name:
                          type: string
                          description: "The display name of the location."
                        address:
                          type: string
                          description: "The address of the location."

  /api/metric_locations/cp_locations/{code}:
    get:
      summary: "Get a care provider location"
      description: "Retrieves detailed information for a single care provider location by its code."
      parameters:
        - name: code
          in: path
          required: true
          description: "The unique identifier for the care provider."
          schema:
            type: string
            example: "1-12345678"
        - name: include_parents
          in: query
          required: false
          description: "Whether to include parent location information."
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: "Detailed information for the requested location."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CareProviderLocation'
        '404':
          description: "Care provider location not found."

  /api/metric_locations/districts/{code}:
    get:
      summary: "Get a district"
      description: "Retrieves detailed information for a district by its code. TBC This endpoint may not be required"
      parameters:
        - name: code
          in: path
          required: true
          description: "The unique identifier for the district."
          schema:
            type: string
            example: "1-12345678"
        - name: include_parents
          in: query
          required: false
          description: "Whether to include parent location information."
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: "Detailed information for the requested location."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/District'
        '404':
          description: "District not found."
  /api/metric_locations/local_authorities/{code}:
      get:
        summary: "Get a local authority"
        description: "Retrieves detailed information for a local authority by its code."
        parameters:
          - name: code
            in: path
            required: true
            description: "The unique identifier for the local authority."
            schema:
              type: string
              example: "1-12345678"
          - name: include_parents
            in: query
            required: false
            description: "Whether to include parent location information."
            schema:
              type: boolean
              default: false
        responses:
          '200':
            description: "Detailed information for the requested location."
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/LocalAuthority'
          '404':
            description: "Local authority not found."
  /api/metric_locations/regions/{code}:
    get:
      summary: "Get a region"
      description: "Retrieves detailed information for a region by its code."
      parameters:
        - name: code
          in: path
          required: true
          description: "The unique identifier for the region."
          schema:
            type: string
            example: "1-12345678"
      responses:
        '200':
          description: "Detailed information for the requested location."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region'
        '404':
          description: "Region not found."
  /api/metric_locations/countries/{code}:
    get:
      summary: "Get a country"
      description: "Retrieves detailed information for a country by its code."
      parameters:
        - name: code
          in: path
          required: true
          description: "The unique identifier for the country."
          schema:
            type: string
            example: "1-12345678"
      responses:
        '200':
          description: "Detailed information for the requested location."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '404':
          description: "Country not found."

  /api/metric_filters/{metric_group_code}:
    get:
      summary: "Get available filters for a group of metrics"
      description: "Retrieves the available filter options for a metric group."
      parameters:
        - $ref: '#/components/parameters/MetricGroupCode'
      responses:
        '200':
          description: "A list of available filter options."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricFilters'
                  

  /api/metrics/{metric_code}/metadata:
    get:
      summary: "Get metadata for a specific metric"
      description: "Retrieves all metadata for a single metric, including its name, numerator, and denominator definitions. "
      parameters:
        - $ref: '#/components/parameters/MetricCode'
      responses:
        '200':
          description: "The metadata for the requested metric."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricMetadata'
        '404':
          description: "Metric not found."

  /api/metrics/{metric_code}/data:
    post:
      summary: "Get time-series or most recent data for a single metric"
      description: "Retrieves data points for a single specified metric across one or more locations. Omit the time_series parameter to get the most recent data point. Include time_series=true to get the time-series."
      parameters:
        - $ref: '#/components/parameters/MetricCode'
        - name: time_series
          in: query
          description: "Boolean whether to return whole time series. If false or omitted, only the most recent data point is returned."
          required: false
          schema:
            type: boolean
            example: False
      requestBody:
        description: "A list of locations to retrieve data for."
        required: true
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: "#/components/schemas/Location"
      responses:
        '200':
          description: "A list of matching metric series for the specified metric."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetricSeries'

# Reusable components
components:
  parameters:
    MetricCode:
      name: metric_code
      in: path
      required: true
      description: "The unique identifier for the metric."
      schema:
        type: string
        example: "bedcount_per_100000_adults_total"
    MetricGroupCode:
      name: metric_group_code
      in: path
      required: true
      description: "The unique identifier for the metric group."
      schema:
        type: string
        example: "bedcount_per_100000_adults"

  schemas:
    CareProviderLocation:
      type: object
      description: "Represents a care provider location"
      properties:
        code:
          type: string
          description: "Unique identifier for the care provider location."
        display_name:
          type: string
          description: "Display name of the care provider location."
        address:
          type: string
          description: "Address of the care provider location."
        geo_data:
          type: object
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/GeoData'
        provider_code:
          type: string
          description: "The parent provider code."
        provider_name:
          type: string
          description: "The parent provider name."
        nominated_individual:
          type: string
          description: "The nominated individual for the care provider location."
        local_authority_code:
          type: string
          nullable: true
          description: "The associated local authority ID."
        local_authority_name:
          type: string
          nullable: true
          description: "The associated local authority name."
        region_code:
          type: string
          nullable: true
          description: "The associated region code."
        region_name:
          type: string
          nullable: true
          description: "The associated region name."
        country_code:
          type: string
          nullable: true
          description: "The associated country code."
        country_name:
          type: string
          nullable: true
          description: "The associated country name."

    District:
      type: object
      description: "Represents a district"
      properties:
        code:
          type: string
          description: "Unique identifier for the district."
        display_name:
          type: string
          description: "Display name of the district."
        geo_data:
          $ref: '#/components/schemas/GeoData'
        local_authority_code:
          type: string
          description: "The associated local authority code."
        region_code:
          type: string
          nullable: true
          description: "The associated region code."
        country_code:
          type: string
          nullable: true
          description: "The associated country code."
    
    LocalAuthority:
      type: object
      description: "Represents a local authority"
      properties:
        code:
          type: string
          description: "Unique identifier for the local authority."
        display_name:
          type: string
          description: "Display name of the local authority."
        geo_data:
          type: object
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/GeoData'
        region_code:
          type: string
          nullable: true
          description: "The associated region code."
        region_name:
            type: string
            nullable: true
            description: "The associated region name."
        country_code:
          type: string
          nullable: true
          description: "The associated country code."
        country_name:
          type: string
          nullable: true
          description: "The associated country name."
    
    Region:
      type: object
      description: "Represents a region"
      properties:
        code:
          type: string
          description: "Unique identifier for the region."
        display_name:
          type: string
          description: "Display name of the region."
        geo_data:
          type: object
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/GeoData'
        country_code:
          type: string
          description: "The associated country code."
        country_name:
          type: string
          description: "The associated country name."

    Country:
      type: object
      description: "Represents a country"
      properties:
        code:
          type: string
          description: "Unique identifier for the country."
        display_name:
          type: string
          description: "Display name of the country."
        geo_data:
          type: object
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/GeoData'

    Postcode:
      type: object
      description: "Geo details for postcode"
      properties:
        sanitised_postcode:
          type: string
          description: "Clean postcode with no whitespace used to search DB"
        display_postcode:
          type: string
          description: "Properly formatted postcode for display"
        geo_data:
          type: object
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/GeoData'
        la_code:
          type: string
          description: "Local authority code."
        la_name:
          type: string
          description: "Local authority name."

    GeoData:
      type: object
      description: "Geographical data for a location."
      properties:
        latitude:
          type: number
          description: "Latitude of the centre point of the location."
        longitude:
          type: number
          description: "Longitude of the centre point of the location."
        polygon:
          type: array
          items:          
            $ref: '#/components/schemas/Coordinate'
            
    Coordinate:
      type: object
      description: "Pair of coordinates"
      properties:
        latitude:
          type: number
          description: "Latitude of the location."
        longitude:
          type: number
          description: "Longitude of the location."
          
    Location:
      type: object
      description: "A location type and code pair."
      properties: 
        location_code:
          type: string
          description: "The locations unique code."
          example: "1-123456789"
        location_type:
          type: string
          description: "The type of this location."
          enum: [la, national, regional]
          default: la
    
    MetricMetadata:
      type: object
      description: "Defines the properties and context of a metric."
      properties:
        metric_code:
          type: string
          description: "The unique identifier for the metric."
        metric_name:
          type: string
          description: "The display name for the metric."
        data_type:
          type: string
          description: "The format of the metric's data, e.g., 'Percentage', 'Currency'."
        data_source:
          type: string
          description: "The source of the data for this metric."
        numerator:
          type: string
          description: "A description of the numerator."
        denominator:
          type: string
          description: "A description of the denominator."

    MetricFilters:
      type: object
      description: "An available filter for a metric, such as bed type."
      properties:
        metric_group_code:
          type: string
          description: "The specific metric group code this filter applies to."
          example: "bedcount_per_100000_adults"
        metrics:
          type: array
          description: "A list of Metric filters belonging to this Metric Group"
          items:
            type: object
            properties:
              metric_code:
                type: string
                description: "The specific metric code this filter applies to."
                example: "bedcount_per_100000_adults_total_general_nursing"
              display_name:
                type: string
                description: "A user-friendly name for the filter value."
                example: "General nursing"

    MetricSeries:
      type: object
      description: "A series of data points at a specific time and location specified in the call for the metric."
      properties:
        metric_code:
          type: string
          description: "The unique identifier for the metric."
        location_code:
          type: string
          description: "The unique identifier for the location."
        series_start_date:
          type: string
          format: date
          nullable: true
          description: "The start date of the metric series. This value is null when a single data point is requested"
        series_end_date:
          type: string
          format: date
          description: "The end date of the metric series."
        series_frequency:
          type: string
          description: "The frequency of data points for the time series."
          enum: [latest, daily, monthly, yearly]
          default: latest
        values:
          type: array
          description: "The calculated data points at the specified frequency. If frequency is 'latest' this array will have one data point"
          items:
            type: number
            format: decimal
            nullable: true
  
  securitySchemes:
    ApiKey:
      type: apiKey
      name: x-api-key
      in: header