#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "argon2-cffi",
# ]
# ///

# Hashes a GOV.UK client secret, as per guidance:
# https://docs.sign-in.service.gov.uk/before-integrating/integrating-third-party-platform/#hash-your-client-secret
# 
# Production usage:
# ./utils/hash_client_secret.py /path/to/CLIENT_SECRET.txt /path/to/SALT.txt
#
# Development:
# ./utils/hash_client_secret.py --interactive --escape

import argon2
from getpass import getpass


def hash_client_secret(client_secret, salt):
    client_secret = client_secret.encode('ascii')
    if salt is not None:
        salt = salt.encode('ascii')
    ph = argon2.PasswordHasher(
        time_cost=2, # aka iterations
        memory_cost=15360, 
        parallelism=1, 
        hash_len=16,
        type=argon2.low_level.Type.ID, # Argon2id
    )
    hashed_secret = ph.hash(client_secret, salt=salt)
    # sanity check
    ph.verify(hashed_secret, client_secret)
    return hashed_secret

if __name__ == "__main__":
    import sys
    # Define the input and output file names
    if "--interactive" in sys.argv:
        client_secret = getpass("Client Secret: ")
        # use autogenerated salt
        salt = None
    else:
        try:
            CLIENT_SECRET_FILENAME = sys.argv[1]
            SALT_FILENAME = sys.argv[2]
        except IndexError:
            print("Please provide paths to the client secret and salt files, or run with --interactive")
            sys.exit(1)

        with open(CLIENT_SECRET_FILENAME) as secretfile:
            client_secret = secretfile.read()

        with open(SALT_FILENAME) as saltfile:
            salt = saltfile.read()

    hashed_secret = hash_client_secret(client_secret, salt)
    if '--escape' in sys.argv:
        print(hashed_secret.replace("$", "$$"))
        print("WARNING: only use escaped version in development")
    else:
        print(hashed_secret)

