import { Indicator } from '@/data/interfaces/Indicator';
import { IndicatorDisplay } from '@/data/interfaces/IndicatorDisplay';

export const barchartIndicators: Indicator[] = [
  {
    metric_id: '1',
    metric_date_type: '',
    metric_date: new Date(2024, 1, 1),
    location_type: 'LA',
    location_id: '1',
    numerator: 0,
    multiplier: 0,
    denominator: 0,
    data_point: 100,
    load_date_time: new Date(2024, 1, 1),
  },
  {
    metric_id: '1',
    metric_date_type: '',
    metric_date: new Date(2024, 1, 1),
    location_type: 'LA',
    location_id: '2',
    numerator: 0,
    multiplier: 0,
    denominator: 0,
    data_point: 150,
    load_date_time: new Date(2024, 1, 1),
  },
  {
    metric_id: '1',
    metric_date_type: '',
    metric_date: new Date(2024, 1, 1),
    location_type: 'LA',
    location_id: '3',
    numerator: 0,
    multiplier: 0,
    denominator: 0,
    data_point: 200,
    load_date_time: new Date(2024, 1, 1),
  },
];

export const linegraphIndicators: Indicator[] = [
  {
    metric_id: '1',
    metric_date_type: '',
    metric_date: new Date(2024, 3, 1),
    location_type: 'LA',
    location_id: '1',
    numerator: 0,
    multiplier: 0,
    denominator: 0,
    data_point: 100,
    load_date_time: new Date(2024, 1, 1),
  },
  {
    metric_id: '1',
    metric_date_type: '',
    metric_date: new Date(2024, 2, 1),
    location_type: 'LA',
    location_id: '1',
    numerator: 0,
    multiplier: 0,
    denominator: 0,
    data_point: 150,
    load_date_time: new Date(2024, 1, 1),
  },
  {
    metric_id: '1',
    metric_date_type: '',
    metric_date: new Date(2024, 1, 1),
    location_type: 'LA',
    location_id: '1',
    numerator: 0,
    multiplier: 0,
    denominator: 0,
    data_point: 200,
    load_date_time: new Date(2024, 1, 1),
  },
];

export const barchartDisplayData: IndicatorDisplay[] = [
  {
    theme: '',
    category: '',
    group_id: '',
    metric_id: '1',
    group: '',
    metric_name: 'barChart',
    description: '',
    numerator: '',
    denominator: '',
    mirrored: '',
    data_source: '',
    filter_age: '',
    filter_support_type: '',
    filter_support_setting: '',
    filter_disabilty_status: '',
    filter_care_provider_type: '',
    filter_bedtype: '',
    metric_type: '',
    aggreation: '',
    graph: '',
    comments: '',
  },
];

export const liengraphDisplayData: IndicatorDisplay[] = [
  {
    theme: '',
    category: '',
    group_id: '',
    metric_id: '',
    group: '',
    metric_name: '',
    description: '',
    numerator: '',
    denominator: '',
    mirrored: '',
    data_source: '',
    filter_age: '',
    filter_support_type: '',
    filter_support_setting: '',
    filter_disabilty_status: '',
    filter_care_provider_type: '',
    filter_bedtype: '',
    metric_type: '',
    aggreation: '',
    graph: '',
    comments: '',
  },
];
